//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQVAT_GetSrvCategory
    {
        public string DescA { get; set; }
        public string ItemFormatFix { get; set; }
        public string ItemFormatSerial { get; set; }
        public Nullable<bool> IsPurchase { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> VatNatID { get; set; }
        public int SrvCategoryID { get; set; }
        public Nullable<int> COMP_CODE { get; set; }
        public string CAT_CODE { get; set; }
        public string DescE { get; set; }
        public string SALES_ACC_CODE { get; set; }
        public string RETURN_ACC_CODE { get; set; }
        public string DISC_ACC_CODE { get; set; }
        public Nullable<System.DateTime> ACTUAL_DATE { get; set; }
        public Nullable<byte> Nature { get; set; }
        public string VatNatureCode { get; set; }
        public string VatNatureDescA { get; set; }
        public string VatNatureDescE { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public string sls_Acc_DescA { get; set; }
        public string sls_Acc_DescE { get; set; }
        public string Ret_Acc_DescA { get; set; }
        public string Ret_Acc_DescE { get; set; }
        public string Dis_Acc_DescA { get; set; }
        public string Dis_Acc_DescE { get; set; }
    }
}
