//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AQVAT_GetService
    {
        public int Itemid { get; set; }
        public string ItemCode { get; set; }
        public string Itm_DescA { get; set; }
        public string Itm_DescE { get; set; }
        public Nullable<int> CompCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string Uom_DescA { get; set; }
        public string Uom_DescE { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<int> VatNatID { get; set; }
        public Nullable<int> SrvCategoryID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> UomID { get; set; }
        public string UomCode { get; set; }
        public string CAT_CODE { get; set; }
        public string Cat_DescA { get; set; }
        public string cat_DescE { get; set; }
        public string VatNatureCode { get; set; }
        public string VatNatureDescA { get; set; }
        public string VatNatureDescE { get; set; }
        public string RefItemCode { get; set; }
        public string OldItemCode { get; set; }
        public string VndItemCode { get; set; }
        public Nullable<bool> IsPurchase { get; set; }
        public int Expr1 { get; set; }
    }
}
