//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVAT_TRANS
    {
        public int COMP_CODE { get; set; }
        public string SYSTEM_CODE { get; set; }
        public string TRTYPE { get; set; }
        public string TRDESCA { get; set; }
        public string TRDESCE { get; set; }
        public string SYSTEMDESCA { get; set; }
        public string SYSTEMDESCE { get; set; }
        public Nullable<int> SEC { get; set; }
        public Nullable<bool> ISAVAILABLE { get; set; }
    }
}
