//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catch_Receipt
    {
        public int ID_Receipt { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string USER_CODE { get; set; }
        public Nullable<int> ID_ORDER_Delivery { get; set; }
        public Nullable<decimal> AmountRequired { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> ShootMoney { get; set; }
        public string Remarks { get; set; }
        public string Data { get; set; }
    }
}
