//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGRE
    {
        public int ID_CAT { get; set; }
        public string Name_CAT { get; set; }
        public Nullable<int> ID_familly_Cat { get; set; }
    }
}
