//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enter_Money
    {
        public int id { get; set; }
        public string Dasc_Name { get; set; }
        public Nullable<decimal> pirce { get; set; }
        public Nullable<int> Num_Day { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string Time { get; set; }
        public string Tr_Type { get; set; }
    }
}
