//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_G_StockMethods
    {
        public int StockMethodID { get; set; }
        public string DescA { get; set; }
        public string DescL { get; set; }
        public string Remarks { get; set; }
    }
}
