//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ItemYearUom
    {
        public int ItemYearUomID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<int> UomId { get; set; }
        public Nullable<decimal> MinUnitPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitWholePrice { get; set; }
        public Nullable<decimal> MinUnitWholePrice { get; set; }
    }
}
