//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ItemSpecsValue
    {
        public int ItemSpecsValue { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> SpecsValueID { get; set; }
    }
}
