//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ItemYear
    {
        public int ItemYearID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<decimal> StarGlobalCost { get; set; }
        public Nullable<decimal> GlobalCost { get; set; }
    }
}
