//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Pur_Tr_ReceiveCharges
    {
        public int ReceiveExpensesID { get; set; }
        public int ReceiveID { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> ChargeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<int> VatType { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<decimal> NetAtferVat { get; set; }
        public Nullable<bool> isPaidByVendor { get; set; }
        public string RefInvoiceNo { get; set; }
        public Nullable<System.DateTime> RefInvoiceDate { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> CashBoxID { get; set; }
    }
}
