//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Pur_TR_ReceiveItems
    {
        public int ReciveDetailsID { get; set; }
        public Nullable<int> ReceiveID { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> RecStockQty { get; set; }
        public Nullable<decimal> ReceiveRecQty { get; set; }
        public Nullable<decimal> RecQty { get; set; }
        public Nullable<decimal> RecUnitPrice { get; set; }
        public Nullable<decimal> VatPrc { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> NetUnitCost { get; set; }
        public Nullable<decimal> BonusQty { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string BatchCode { get; set; }
        public string BarCode { get; set; }
        public Nullable<decimal> StockAvailableQty { get; set; }
        public Nullable<decimal> StockUnitCost { get; set; }
        public Nullable<decimal> NewUnitCost { get; set; }
        public Nullable<decimal> TotRetQty { get; set; }
        public Nullable<decimal> UnitAddCost { get; set; }
        public Nullable<decimal> RecUnitPriceFC { get; set; }
    }
}
