//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_Catch_Receipt
    {
        public int ID_Receipt { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string USER_CODE { get; set; }
        public Nullable<decimal> AmountRequired { get; set; }
        public Nullable<decimal> ShootMoney { get; set; }
        public string Remarks { get; set; }
        public string CustomerCODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string NAMEE { get; set; }
        public string CUSTOMER_ADDRES { get; set; }
        public string CUSTOMER_ADDRES_2 { get; set; }
        public string PHONE { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<decimal> CreditLimitFC { get; set; }
        public Nullable<int> CreditPeriod { get; set; }
        public Nullable<decimal> OpenBalanceFC { get; set; }
        public Nullable<decimal> Openbalance { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> DebitFC { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<bool> IsCreditCustomer { get; set; }
        public string USER_PASSWORD { get; set; }
        public bool USER_ACTIVE { get; set; }
        public string USER_NAME { get; set; }
        public string Data { get; set; }
    }
}
