//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_GetItemYearUom
    {
        public int ItemYearUomID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> FinYear { get; set; }
        public Nullable<int> UomId { get; set; }
        public Nullable<decimal> MinUnitPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitWholePrice { get; set; }
        public Nullable<decimal> MinUnitWholePrice { get; set; }
        public string UomCode { get; set; }
        public string DescA { get; set; }
        public string DescE { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<bool> IsRetailSales { get; set; }
        public Nullable<bool> IsWholeSales { get; set; }
        public Nullable<bool> IsPurchase { get; set; }
        public Nullable<bool> IsStock { get; set; }
    }
}
