//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings_Report
    {
        public int ID_Report { get; set; }
        public string ID_Button_Print { get; set; }
        public string Name_Report { get; set; }
        public string Name_Stored_Report { get; set; }
    }
}
